
function defineCards() {
  //ore, stone, brick, wood, textile, glass, papyrus, coins
  //military, vp, coins
  //All cards that have chained descendents must be defined before their children. This car be achieved by making declarations in age order
  cards = [
    {
    name:"Lumber Yard",
    minPlayers: 3,
    age: 1,
    color: 'brown',
    resource: '00010000',
    cost: '00000000',
  },
    {
    name:"Lumber Yard",
    minPlayers: 4,
    age: 1,
    color: 'brown',
    resource: '00010000',
    cost: '00000000',
  },
    {
    name:"Stone Pit",
    minPlayers: 3,
    age: 1,
    color: 'brown',
    resource: '01000000',
    cost: '00000000',
  },
    {
    name:"Stone Pit",
    minPlayers: 5,
    age: 1,
    color: 'brown',
    resource: '01000000',
    cost: '00000000',
  },
    {
    name:"Clay Pool",
    minPlayers: 3,
    age: 1,
    color: 'brown',
    resource: '00100000',
    cost: '00000000',
  },
    {
    name:"Clay Pool",
    minPlayers: 5,
    age: 1,
    color: 'brown',
    resource: '00100000',
    cost: '00000000',
  },
    {
    name:"Ore Vein",
    minPlayers: 3,
    age: 1,
    color: 'brown',
    resource: '10000000',
    cost: '00000000',
  },
    {
    name:"Ore Vein",
    minPlayers: 4,
    age: 1,
    color: 'brown',
    resource: '10000000',
    cost: '00000000',
  },
    {
    name:"Tree Farm",
    minPlayers: 6,
    age: 1,
    color: 'brown',
    resource: ['00100000','00010000'],
    cost: '00000001',
  },
    {
    name:"Excavation",
    minPlayers: 4,
    age: 1,
    color: 'brown',
    resource: ['01000000','00010000'],
    cost: '00000001',
  },
    {
    name:"Clay Pit",
    minPlayers: 3,
    age: 1,
    color: 'brown',
    resource: ['00100000','10000000'],
    cost: '00000001',
  },
    {
    name:"Timber Yard",
    minPlayers: 3,
    age: 1,
    color: 'brown',
    resource: ['01000000','00010000'],
    cost: '00000001',
  },
    {
    name:"Forest Cave",
    minPlayers: 5,
    age: 1,
    color: 'brown',
    resource: ['10000000','00010000'],
    cost: '00000001',
  },
    {
    name:"Mine",
    minPlayers: 6,
    age: 1,
    color: 'brown',
    resource: ['10000000','01000000'],
    cost: '00000001',
  },
    {
    name:"Loom",
    minPlayers: 3,
    age: 1,
    color: 'grey',
    resource: '00001000',
    cost: '00000000',
  },
    {
    name:"Loom",
    minPlayers: 6,
    age: 1,
    color: 'grey',
    resource: '00001000',
    cost: '00000000',
  },
    {
    name:"Glassworks",
    minPlayers: 3,
    age: 1,
    color: 'grey',
    resource: '00000100',
    cost: '00000000',
  },
    {
    name:"Glassworks",
    minPlayers: 6,
    age: 1,
    color: 'grey',
    resource: '00000100',
    cost: '00000000',
  },
    {
    name:"Press",
    minPlayers: 3,
    age: 1,
    color: 'grey',
    resource: '00000010',
    cost: '00000000',
  },
    {
    name:"Press",
    minPlayers: 6,
    age: 1,
    color: 'grey',
    resource: '00000010',
    cost: '00000000',
  },
    {
    name:"Pawnshop",
    minPlayers: 4,
    age: 1,
    color: 'blue',
    boon: 3,
    cost: '00000000',
  },
    {
    name:"Pawnshop",
    minPlayers: 7,
    age: 1,
    color: 'blue',
    boon: 3,
    cost: '00000000',
  },
  {
    name:"Baths",
    minPlayers: 3,
    age: 1,
    color: 'blue',
    boon: 3,
    cost: '01000000',
    chainTo: 'Aqueduct',
  },
  {
    name:"Baths",
    minPlayers: 7,
    age: 1,
    color: 'blue',
    boon: 3,
    cost: '01000000',
    chainTo: 'Aqueduct',
  },
  {
    name:"Altar",
    minPlayers: 3,
    age: 1,
    color: 'blue',
    boon: 2,
    cost: '00000000',
    chainTo: 'Temple',
  },
  {
    name:"Altar",
    minPlayers: 5,
    age: 1,
    color: 'blue',
    boon: 2,
    cost: '00000000',
    chainTo: 'Temple',
  },
  {
    name:"Theater",
    minPlayers: 3,
    age: 1,
    color: 'blue',
    boon: 2,
    cost: '00000000',
    chainTo: 'Statue',
  },
  {
    name:"Theater",
    minPlayers: 6,
    age: 1,
    color: 'blue',
    boon: 2,
    cost: '00000000',
    chainTo: 'Statue',
  },
  {
    name:"Tavern",
    minPlayers: 4,
    age: 1,
    color: 'yellow',
    boon: '005',
    cost: '00000000',
  },
  {
    name:"Tavern",
    minPlayers: 5,
    age: 1,
    color: 'yellow',
    boon: '005',
    cost: '00000000',
  },
  {
    name:"Tavern",
    minPlayers: 7,
    age: 1,
    color: 'yellow',
    boon: '005',
    cost: '00000000',
  },
  {
    name:"East Trading Post",
    minPlayers: 3,
    age: 1,
    color: 'yellow',
    boon: 'tradebasicright',
    cost: '00000000',
    chainTo: 'Forum',
  },
  {
    name:"East Trading Post",
    minPlayers: 7,
    age: 1,
    color: 'yellow',
    boon: 'tradebasicright',
    cost: '00000000',
    chainTo: 'Forum',
  },
  {
    name:"West Trading Post",
    minPlayers: 3,
    age: 1,
    color: 'yellow',
    boon: 'tradebasicleft',
    cost: '00000000',
    chainTo: 'Forum',
  },
  {
    name:"West Trading Post",
    minPlayers: 7,
    age: 1,
    color: 'yellow',
    boon: 'tradebasicleft',
    cost: '00000000',
    chainTo: 'Forum',
  },
  {
    name:"MarketPlace",
    minPlayers: 3,
    age: 1,
    color: 'yellow',
    boon: 'tradeadv',
    cost: '00000000',
    chainTo: 'Caravansery',
  },
  {
    name:"MarketPlace",
    minPlayers: 6,
    age: 1,
    color: 'yellow',
    boon: 'tradeadv',
    cost: '00000000',
    chainTo: 'Caravansery',
  },
  {
    name:"Stockade",
    minPlayers: 3,
    age: 1,
    color: 'red',
    boon: '100',
    cost: '00010000',
  },
  {
    name:"Stockade",
    minPlayers: 7,
    age: 1,
    color: 'red',
    boon: '100',
    cost: '00010000',
  },
  {
    name:"Barracks",
    minPlayers: 3,
    age: 1,
    color: 'red',
    boon: '100',
    cost: '10000000',
  },
  {
    name:"Barracks",
    minPlayers: 5,
    age: 1,
    color: 'red',
    boon: '100',
    cost: '10000000',
  },
  {
    name:"Guard Tower",
    minPlayers: 3,
    age: 1,
    color: 'red',
    boon: '100',
    cost: '00100000',
  },
  {
    name:"Guard Tower",
    minPlayers: 4,
    age: 1,
    color: 'red',
    boon: '100',
    cost: '00100000',
  },
  {
    name:"Apothecary",
    minPlayers: 3,
    age: 1,
    color: 'green',
    tech: 'compass',
    cost: '00001000',
    chainTo: ['Stables', 'Dispensary'],
  },
  {
    name:"Apothecary",
    minPlayers: 5,
    age: 1,
    color: 'green',
    tech: 'compass',
    cost: '00001000',
    chainTo: ['Stables', 'Dispensary'],
  },
  {
    name:"Workshop",
    minPlayers: 3,
    age: 1,
    color: 'green',
    tech: 'gear',
    cost: '00000100',
    chainTo: ['Archery Range', 'Laboratory'],
  },
  {
    name:"Workshop",
    minPlayers: 7,
    age: 1,
    color: 'green',
    tech: 'gear',
    cost: '00000100',
    chainTo: ['Archery Range', 'Laboratory'],
  },
  {
    name:"Scriptorium",
    minPlayers: 3,
    age: 1,
    color: 'green',
    tech: 'tablet',
    cost: '00000010',
    chainTo: ['Courthouse', 'Library'],
  },
  {
    name:"Scriptorium",
    minPlayers: 4,
    age: 1,
    color: 'green',
    tech: 'tablet',
    cost: '00000010',
    chainTo: ['Courthouse', 'Library'],
  },
  {
    name:"Sawmill",
    minPlayers: 3,
    age: 2,
    color: 'brown',
    resource: '00020000',
    cost: '00000001',
  },
  {
    name:"Sawmill",
    minPlayers: 4,
    age: 2,
    color: 'brown',
    resource: '00020000',
    cost: '00000001',
  },
  {
    name:"Quarry",
    minPlayers: 3,
    age: 2,
    color: 'brown',
    resource: '02000000',
    cost: '00000001',
  },
  {
    name:"Quarry",
    minPlayers: 4,
    age: 2,
    color: 'brown',
    resource: '02000000',
    cost: '00000001',
  },
  {
    name:"Brickyard",
    minPlayers: 3,
    age: 2,
    color: 'brown',
    resource: '00200000',
    cost: '00000001',
  },
  {
    name:"Brickyard",
    minPlayers: 4,
    age: 2,
    color: 'brown',
    resource: '00200000',
    cost: '00000001',
  },
  {
    name:"Foundry",
    minPlayers: 3,
    age: 2,
    color: 'brown',
    resource: '20000000',
    cost: '00000001',
  },
  {
    name:"Foundry",
    minPlayers: 4,
    age: 2,
    color: 'brown',
    resource: '20000000',
    cost: '00000001',
  },
    {
    name:"Loom",
    minPlayers: 3,
    age: 2,
    color: 'grey',
    resource: '00001000',
    cost: '00000000',
  },
    {
    name:"Loom",
    minPlayers: 5,
    age: 2,
    color: 'grey',
    resource: '00001000',
    cost: '00000000',
  },
    {
    name:"Glassworks",
    minPlayers: 3,
    age: 2,
    color: 'grey',
    resource: '00000100',
    cost: '00000000',
  },
    {
    name:"Glassworks",
    minPlayers: 5,
    age: 2,
    color: 'grey',
    resource: '00000100',
    cost: '00000000',
  },
    {
    name:"Press",
    minPlayers: 3,
    age: 2,
    color: 'grey',
    resource: '00000010',
    cost: '00000000',
  },
    {
    name:"Press",
    minPlayers: 5,
    age: 2,
    color: 'grey',
    resource: '00000010',
    cost: '00000000',
  },
    {
    name:"Aqueduct",
    minPlayers: 3,
    age: 2,
    color: 'blue',
    boon: 5,
    cost: '03000000',
    chainFrom: 'Baths',
  },
    {
    name:"Aqueduct",
    minPlayers: 7,
    age: 2,
    color: 'blue',
    boon: 5,
    cost: '03000000',
    chainFrom: 'Baths',
  },
    {
    name:"Temple",
    minPlayers: 3,
    age: 2,
    color: 'blue',
    boon: 3,
    cost: '00110100',
    chainTo: 'Pantheon',
    chainFrom: 'Altar',
  },
    {
    name:"Temple",
    minPlayers: 6,
    age: 2,
    color: 'blue',
    boon: 4,
    cost: '00110100',
    chainTo: 'Pantheon',
    chainFrom: 'Altar',
  },
    {
    name:"Statue",
    minPlayers: 3,
    age: 2,
    color: 'blue',
    boon: 4,
    cost: '20010000',
    chainTo: 'Gardens',
    chainFrom: 'Theater',
  },
    {
    name:"Statue",
    minPlayers: 7,
    age: 2,
    color: 'blue',
    boon: 4,
    cost: '20010000',
    chainTo: 'Gardens',
    chainFrom: 'Theater',
  },
    {
    name:"Courthouse",
    minPlayers: 3,
    age: 2,
    color: 'blue',
    boon: 4,
    cost: '00201000',
    chainFrom: 'Scriptorium',
  },
    {
    name:"Courthouse",
    minPlayers: 5,
    age: 2,
    color: 'blue',
    boon: 4,
    cost: '00201000',
    chainFrom: 'Scriptorium',
  },
    {
    name:"Forum",
    minPlayers: 3,
    age: 2,
    color: 'yellow',
    boon: 'anyadv',
    cost: '00200000',
    chainTo: 'Haven',
    chainFrom: ['East Trading Post', 'West Trading Post'],
  },
    {
    name:"Forum",
    minPlayers: 6,
    age: 2,
    color: 'yellow',
    boon: 'anyadv',
    cost: '00200000',
    chainTo: 'Haven',
    chainFrom: ['East Trading Post', 'West Trading Post'],
  },
    {
    name:"Forum",
    minPlayers: 7,
    age: 2,
    color: 'yellow',
    boon: 'anyadv',
    cost: '00200000',
    chainTo: 'Haven',
    chainFrom: ['East Trading Post', 'West Trading Post'],
  },
    {
    name:"Caravansery",
    minPlayers: 3,
    age: 2,
    color: 'yellow',
    boon: 'anybasic',
    cost: '00020000',
    chainTo: 'Haven',
    chainFrom: 'MarketPlace',
  },
    {
    name:"Caravansery",
    minPlayers: 5,
    age: 2,
    color: 'yellow',
    boon: 'anybasic',
    cost: '00020000',
    chainTo: 'Lighthouse',
    chainFrom: 'MarketPlace',
  },
    {
    name:"Caravansery",
    minPlayers: 6,
    age: 2,
    color: 'yellow',
    boon: 'anybasic',
    cost: '00020000',
    chainTo: 'Lighthouse',
    chainFrom: 'MarketPlace',
  },
    {
    name:"Vineyard",
    minPlayers: 3,
    age: 2,
    color: 'yellow',
    boon: '00x',
    cost: '00000000',
    x: ['lsr', 'brown', 1],
  },
    {
    name:"Vineyard",
    minPlayers: 6,
    age: 2,
    color: 'yellow',
    boon: '00x',
    cost: '00000000',
    x: ['lsr', 'brown', 1],
  },
    {
    name:"Bazar",
    minPlayers: 4,
    age: 2,
    color: 'yellow',
    boon: '00x',
    cost: '00000000',
    x: ['lsr', 'grey', 2],
  },
    {
    name:"Bazar",
    minPlayers: 7,
    age: 2,
    color: 'yellow',
    boon: '00x',
    cost: '00000000',
    x: ['lsr', 'grey', 2],
  },
    {
    name:"Walls",
    minPlayers: 3,
    age: 2,
    color: 'red',
    boon: '200',
    cost: '03000000',
    chainTo: 'Fortifications',
  },
    {
    name:"Walls",
    minPlayers: 7,
    age: 2,
    color: 'red',
    boon: '200',
    cost: '03000000',
    chainTo: 'Fortifications',
  },
    {
    name:"Training Ground",
    minPlayers: 4,
    age: 2,
    color: 'red',
    boon: '200',
    cost: '20010000',
    chainTo: 'Circus',
  },
    {
    name:"Training Ground",
    minPlayers: 6,
    age: 2,
    color: 'red',
    boon: '200',
    cost: '20010000',
    chainTo: 'Circus',
  },
    {
    name:"Training Ground",
    minPlayers: 7,
    age: 2,
    color: 'red',
    boon: '200',
    cost: '20010000',
    chainTo: 'Circus',
  },
    {
    name:"Stables",
    minPlayers: 3,
    age: 2,
    color: 'red',
    boon: '200',
    cost: '10110000',
    chainFrom: 'Apothecary',
  },
    {
    name:"Stables",
    minPlayers: 5,
    age: 2,
    color: 'red',
    boon: '200',
    cost: '10110000',
    chainFrom: 'Apothecary',
  },
    {
    name:"Archery Range",
    minPlayers: 3,
    age: 2,
    color: 'red',
    boon: '200',
    cost: '10020000',
    chainFrom: 'Workshop',
  },
    {
    name:"Archery Range",
    minPlayers: 6,
    age: 2,
    color: 'red',
    boon: '200',
    cost: '10020000',
    chainFrom: 'Workshop',
  },
    {
    name:"Dispensary",
    minPlayers: 3,
    age: 2,
    color: 'green',
    tech: 'compass',
    cost: '20000010',
    chainFrom: 'Apothecary',
    chainTo: ['Arena', 'Lodge', ],
  },
    {
    name:"Dispensary",
    minPlayers: 4,
    age: 2,
    color: 'green',
    tech: 'compass',
    cost: '20000100',
    chainFrom: 'Apothecary',
    chainTo: ['Arena', 'Lodge', ],
  },
    {
    name:"Laboratory",
    minPlayers: 3,
    age: 2,
    color: 'green',
    tech: 'gear',
    cost: '00200010',
    chainFrom: 'Workshop',
    chainTo: ['Siege Workshop', 'Observatory', ],
  },
    {
    name:"Laboratory",
    minPlayers: 5,
    age: 2,
    color: 'green',
    tech: 'gear',
    cost: '00200010',
    chainFrom: 'Workshop',
    chainTo: ['Siege Workshop', 'Observatory', ],
  },
    {
    name:"Library",
    minPlayers: 3,
    age: 2,
    color: 'green',
    tech: 'tablet',
    cost: '02001000',
    chainFrom: 'Scriptorium',
    chainTo: ['Senate', 'University', ],
  },
    {
    name:"Library",
    minPlayers: 6,
    age: 2,
    color: 'green',
    tech: 'tablet',
    cost: '02001000',
    chainFrom: 'Scriptorium',
    chainTo: ['Senate', 'University', ],
  },
    {
    name:"School",
    minPlayers: 3,
    age: 2,
    color: 'green',
    tech: 'tablet',
    cost: '00010010',
    chainTo: ['Academy', 'Study', ],
  },
    {
    name:"School",
    minPlayers: 7,
    age: 2,
    color: 'green',
    tech: 'tablet',
    cost: '00010010',
    chainTo: ['Academy', 'Study', ],
  },
    {
    name:"Pantheon",
    minPlayers: 3,
    age: 3,
    color: 'blue',
    boon: 7,
    cost: '10201110',
    chainFrom: 'Temple',
  },
    {
    name:"Pantheon",
    minPlayers: 6,
    age: 3,
    color: 'blue',
    boon: 7,
    cost: '10201110',
    chainFrom: 'Temple',
  },
    {
    name:"Gardens",
    minPlayers: 3,
    age: 3,
    color: 'blue',
    boon: 5,
    cost: '00210000',
    chainFrom: 'Statue',
  },
    {
    name:"Gardens",
    minPlayers: 4,
    age: 3,
    color: 'blue',
    boon: 5,
    cost: '00210000',
    chainFrom: 'Statue',
  },
    {
    name:"Town Hall",
    minPlayers: 3,
    age: 3,
    color: 'blue',
    boon: 6,
    cost: '12000100',
  },
    {
    name:"Town Hall",
    minPlayers: 5,
    age: 3,
    color: 'blue',
    boon: 6,
    cost: '12000100',
  },
    {
    name:"Town Hall",
    minPlayers: 6,
    age: 3,
    color: 'blue',
    boon: 6,
    cost: '12000100',
  },
    {
    name:"Palace",
    minPlayers: 3,
    age: 3,
    color: 'blue',
    boon: 8,
    cost: '11111110',
  },
    {
    name:"Palace",
    minPlayers: 7,
    age: 3,
    color: 'blue',
    boon: 8,
    cost: '11111110',
  },
    {
    name:"Senate",
    minPlayers: 3,
    age: 3,
    color: 'blue',
    boon: 6,
    cost: '11020000',
    chainFrom: "Library",
  },
    {
    name:"Senate",
    minPlayers: 5,
    age: 3,
    color: 'blue',
    boon: 6,
    cost: '11020000',
    chainFrom: "Library",
  },
    {
    name:"Haven",
    minPlayers: 3,
    age: 3,
    color: 'yellow',
    boon: '0xx',
    cost: '10011000',
    chainFrom: "Forum",
    x: ['s', 'brown', 1],
  },
    {
    name:"Haven",
    minPlayers: 4,
    age: 3,
    color: 'yellow',
    boon: '0xx',
    cost: '10011000',
    chainFrom: "Forum",
    x: ['s', 'brown', 2],
  },
    {
    name:"Lighthouse",
    minPlayers: 3,
    age: 3,
    color: 'yellow',
    boon: '0xx',
    cost: '01000100',
    chainFrom: "Caravansery",
    x: ['s', 'yellow', 1],
  },
    {
    name:"Lighthouse",
    minPlayers: 6,
    age: 3,
    color: 'yellow',
    boon: '0xx',
    cost: '01000100',
    chainFrom: "Caravansery",
    x: ['s', 'yellow', 1],
  },
    {
    name:"Chamber of Commerce",
    minPlayers: 4,
    age: 3,
    color: 'yellow',
    boon: '0xx',
    cost: '00200010',
    x: ['s', 'grey', 2],
  },
    {
    name:"Chamber of Commerce",
    minPlayers: 6,
    age: 3,
    color: 'yellow',
    boon: '0xx',
    cost: '00200010',
    x: ['s', 'grey', 2],
  },
    {
    name:"Arena",
    minPlayers: 3,
    age: 3,
    color: 'yellow',
    boon: '0xy',
    cost: '12000000',
    x: ['s', 'stages', 1],
    y: ['s', 'stages', 3],
    chainFrom: "Dispensary",
  },
    {
    name:"Arena",
    minPlayers: 5,
    age: 3,
    color: 'yellow',
    boon: '0xy',
    cost: '12000000',
    x: ['s', 'stages', 1],
    y: ['s', 'stages', 3],
    chainFrom: "Dispensary",
  },
    {
    name:"Arena",
    minPlayers: 7,
    age: 3,
    color: 'yellow',
    boon: '0xy',
    cost: '12000000',
    x: ['s', 'stages', 1],
    y: ['s', 'stages', 3],
    chainFrom: "Dispensary",
  },
    {
    name:"Fortifications",
    minPlayers: 3,
    age: 3,
    color: 'red',
    boon: '300',
    cost: '31000000',
    chainFrom: "Walls",
  },
    {
    name:"Fortifications",
    minPlayers: 7,
    age: 3,
    color: 'red',
    boon: '300',
    cost: '31000000',
    chainFrom: "Walls",
  },
    {
    name:"Circus",
    minPlayers: 4,
    age: 3,
    color: 'red',
    boon: '300',
    cost: '13000000',
    chainFrom: "Training Ground",
  },
    {
    name:"Circus",
    minPlayers: 5,
    age: 3,
    color: 'red',
    boon: '300',
    cost: '13000000',
    chainFrom: "Training Ground",
  },
    {
    name:"Circus",
    minPlayers: 6,
    age: 3,
    color: 'red',
    boon: '300',
    cost: '13000000',
    chainFrom: "Training Ground",
  },
    {
    name:"Arsenal",
    minPlayers: 3,
    age: 3,
    color: 'red',
    boon: '300',
    cost: '10021000',
  },
    {
    name:"Arsenal",
    minPlayers: 4,
    age: 3,
    color: 'red',
    boon: '300',
    cost: '10021000',
  },
    {
    name:"Arsenal",
    minPlayers: 7,
    age: 3,
    color: 'red',
    boon: '300',
    cost: '10021000',
  },
    {
    name:"Siege Workshop",
    minPlayers: 3,
    age: 3,
    color: 'red',
    boon: '300',
    cost: '00310000',
    chainFrom: "Laboratory",
  },
    {
    name:"Siege Workshop",
    minPlayers: 5,
    age: 3,
    color: 'red',
    boon: '300',
    cost: '00310000',
    chainFrom: "Laboratory",
  },
    {
    name:"Lodge",
    minPlayers: 3,
    age: 3,
    color: 'green',
    tech: 'compass',
    cost: '00201010',
    chainFrom: "Dispensary",
  },
    {
    name:"Lodge",
    minPlayers: 6,
    age: 3,
    color: 'green',
    tech: 'compass',
    cost: '00201010',
    chainFrom: "Dispensary",
  },
    {
    name:"Observatory",
    minPlayers: 3,
    age: 3,
    color: 'green',
    tech: 'gear',
    cost: '20001100',
    chainFrom: "Laboratory",
  },
    {
    name:"Observatory",
    minPlayers: 7,
    age: 3,
    color: 'green',
    tech: 'gear',
    cost: '20001100',
    chainFrom: "Laboratory",
  },
    {
    name:"University",
    minPlayers: 3,
    age: 3,
    color: 'green',
    tech: 'tablet',
    cost: '00020110',
    chainFrom: "Library",
  },
    {
    name:"University",
    minPlayers: 4,
    age: 3,
    color: 'green',
    tech: 'tablet',
    cost: '00020110',
    chainFrom: "Library",
  },
    {
    name:"Academy",
    minPlayers: 3,
    age: 3,
    color: 'green',
    tech: 'compass',
    cost: '03000100',
    chainFrom: "School",
  },
    {
    name:"Academy",
    minPlayers: 7,
    age: 3,
    color: 'green',
    tech: 'compass',
    cost: '03000100',
    chainFrom: "School",
  },
    {
    name:"Study",
    minPlayers: 3,
    age: 3,
    color: 'green',
    tech: 'gear',
    cost: '00011010',
    chainFrom: "School",
  },
    {
    name:"Study",
    minPlayers: 5,
    age: 3,
    color: 'green',
    tech: 'gear',
    cost: '00011010',
    chainFrom: "School",
  },
    {
    name:"Workers Guild",
    minPlayers: 0,
    age: 3,
    color: 'purple',
    cost: '21110000',
    boon: '0x0',
    x: ['lr', 'brown', 1],
  },
    {
    name:"Craftmens Guild",
    minPlayers: 0,
    age: 3,
    color: 'purple',
    cost: '22000000',
    boon: '0x0',
    x: ['lr', 'grey', 1],
  },
    {
    name:"Traders Guild",
    minPlayers: 0,
    age: 3,
    color: 'purple',
    cost: '00001110',
    boon: '0x0',
    x: ['lr', 'yellow', 1],
  },
    {
    name:"Philosophers Guild",
    minPlayers: 0,
    age: 3,
    color: 'purple',
    cost: '00301010',
    boon: '0x0',
    x: ['lr', 'green', 1],
  },
    {
    name:"Spy Guild",
    minPlayers: 0,
    age: 3,
    color: 'purple',
    cost: '00300100',
    boon: '0x0',
    x: ['lr', 'red', 1],
  },
    {
    name:"Strategists Guild",
    minPlayers: 0,
    age: 3,
    color: 'purple',
    cost: '21001000',
    boon: '0x0',
    x: ['lr', 'losses', 1],
  },
    {
    name:"Shipowners Guild",
    minPlayers: 0,
    age: 3,
    color: 'purple',
    cost: '00001110',
    boon: '0x0',
    x: ['s', ['brown', 'grey', 'purple'], 1, 'each'],
  },
    {
    name:"Scientists Guild",
    minPlayers: 0,
    age: 3,
    color: 'purple',
    cost: '20020010',
    boon: 'anytech',
  },
    {
    name:"Magistrates Guild",
    minPlayers: 0,
    age: 3,
    color: 'purple',
    cost: '01031000',
    boon: '0x0',
    x: ['lr', 'blue', 1],
  },
    {
    name:"Builders Guild",
    minPlayers: 0,
    age: 3,
    color: 'purple',
    cost: '02200100',
    boon: '0x0',
    x: ['lsr', 'stage', 1],
  },
  ];

  Cards.remove({});
  _.each(cards, function(card) {
    var acceptableName = card.name.replace(/\s+/g, '');
    //build chainFrom indexes, using regex to make variables viable
    if (card.chainFrom) {
      if (typeof card.chainFrom == "string") {
        var acceptableChainFrom =  card.chainFrom.replace(/\s+/g, '');
        card.chainFromId = eval(acceptableChainFrom);
      } else  {
        card.chainFromId = [];
        _.each(card.chainFrom, function(idArray) {
          var acceptableChainFrom =  idArray.replace(/\s+/g, '');
          card.chainFromId = card.chainFromId.concat(eval(acceptableChainFrom));
        })
      }
    }

    // define so as to return the collection Id as a variable set to the card name for use
    if (typeof eval('this.' + acceptableName) === "undefined") {
      eval( acceptableName + " = []");
    }

      //console.log(eval('acceptableName'));
    eval(acceptableName + '.push(Cards.insert(card))');
  });
}
